# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ConfKit
email: contact@confkit.org
description: >- # this means to ignore newlines until "baseurl:"
  ConfKit is a French non-profit organization. Our goal is to promote knowledge transfers in the tech industry. 
  We think the only way to be a better developer is to learn from others - but the best way to become an expert is to *teach* others! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://confkit.github.io" # the base hostname & protocol for your site, e.g. http://example.com
first_published: 2021 # if migrating another site, the year of your first publish

twitter_username: confkitorg
github_username:  confkit

# Build settings
markdown: kramdown
sass:
  style: compressed
exclude: ["Gemfile*", "Guardfile*", ".git*", "resources", "*.sh"]